# Generated by Django 4.2.7 on 2025-07-28 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GratitudeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Give your entry a meaningful title', max_length=200)),
                ('content', models.TextField(help_text='What are you grateful for today?')),
                ('mood', models.CharField(choices=[('excellent', '😄 Excellent'), ('good', '😊 Good'), ('okay', '😐 Okay'), ('difficult', '😔 Difficult'), ('challenging', '😰 Challenging')], default='good', max_length=20)),
                ('tags', models.CharField(blank=True, help_text='Optional tags separated by commas (e.g., family, work, health)', max_length=200)),
                ('is_private', models.BooleanField(default=True, help_text='Keep this entry private')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gratitude_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gratitude Entry',
                'verbose_name_plural': 'Gratitude Entries',
                'ordering': ['-created_at'],
            },
        ),
    ]
