# Generated by Django 4.2.7 on 2025-07-31 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gratitudeentry',
            name='title',
            field=models.CharField(blank=True, help_text='Give your entry a meaningful title (optional)', max_length=200),
        ),
    ]
